name: Run slack pipeline from slack_pipeline.py
'on':
  schedule:
  - cron: 0 13 * * 1
  workflow_dispatch: null
  push:
    branches:
      - main
env:
  RUNTIME__DLTHUB_DSN: ${{ secrets.RUNTIME__DLTHUB_DSN }}
  SOURCES__SLACK__ACCESS_TOKEN: ${{ secrets.SOURCES__SLACK__ACCESS_TOKEN }}
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: dlthub-analytics
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: slack-backup@dlthub-analytics.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}
jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'
  run_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements_github_action.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements_github_action.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - name: Run pipeline script
      run: python 'slack_pipeline.py'
